[package]
name = "ledger-fidelity-401k-parser"
version = "0.1.0"
authors = ["Colin Dean <git@cad.cx>"]

[dependencies]
csv = "1.0.0-beta.5"
serde = "1"
serde_derive = "1"
steel-cent = "0.2"
chrono ="0.4"
